alter table TS_TIME_ENTRY add constraint FK_TS_TIME_ENTRY_ACTIVITY_TYPE_ID foreign key (ACTIVITY_TYPE_ID) references TS_ACTIVITY_TYPE(ID);
create index IDX_TS_TIME_ENTRY_ACTIVITY_TYPE on TS_TIME_ENTRY (ACTIVITY_TYPE_ID);
